### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Vulturu1** [d4az/hack-gmail#2]
When trying to use my own password list the program gives me this output:

Traceback (most recent call last):
  File "/home/kali/hack-gmail/hack-gmail.py", line 40, in <module>
    passswfile = open(passswfile, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/kali/hack-gmail/passlist.txt'

Not sure why it does this even though the fils IS in the right spot

**Comment by ebadfd** [comment]
hi that error happens because the file is missing or the file doesn't have permission to run please check the file path or run the script as root

thanks.
